# vcluster-dev.yaml
apiVersion: v1
kind: ServiceAccount
metadata:
  name: vcluster-dev
  namespace: host-vcluster-1
---
kind: Role
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: vcluster-dev
  namespace: host-vcluster-1
rules:
  - apiGroups: [""]
    resources: ["configmaps", "secrets", "services", "services/proxy", "pods", "pods/proxy", "pods/attach", "pods/portforward", "pods/exec", "pods/log", "events", "endpoints", "persistentvolumeclaims"]
    verbs: ["*"]
  - apiGroups: ["networking.k8s.io"]
    resources: ["ingresses"]
    verbs: ["*"]
  - apiGroups: [""]
    resources: ["namespaces"]
    verbs: ["get", "list", "watch"]
  - apiGroups: ["apps"]
    resources: ["statefulsets"]
    verbs: ["get", "list", "watch"]
---
kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: vcluster-dev
  namespace: host-vcluster-1
subjects:
  - kind: ServiceAccount
    name: vcluster-dev
roleRef:
  kind: Role
  name: vcluster-dev
  apiGroup: rbac.authorization.k8s.io
---
apiVersion: v1
kind: Service
metadata:
  name: vcluster-dev
  namespace: host-vcluster-1
spec:
  type: ClusterIP
  ports:
    - name: https
      port: 443
      targetPort: 8443
      protocol: TCP
  selector:
    app: vcluster-dev
---
apiVersion: v1
kind: Service
metadata:
  name: vcluster-dev-headless
  namespace: host-vcluster-1
spec:
  ports:
    - name: https
      port: 443
      targetPort: 8443
      protocol: TCP
  clusterIP: None
  selector:
    app: vcluster-dev
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: vcluster-dev
  namespace: host-vcluster-1
  labels:
    app: vcluster-dev
spec:
  serviceName: vcluster-dev-headless
  replicas: 1
  selector:
    matchLabels:
      app: vcluster-dev
  template:
    metadata:
      labels:
        app: vcluster-dev
    spec:
      terminationGracePeriodSeconds: 10
      serviceAccountName: vcluster-dev
      containers:
      - image: rancher/k3s:v1.21.5+k3s2
        name: vcluster-dev-0
        command:
          - "/bin/k3s"
        args:
          - "server"
          - "--write-kubeconfig=/k3s-config/kube-config.yaml"
          - "--data-dir=/data"
          - "--disable=traefik,servicelb,metrics-server,local-storage"
          - "--disable-network-policy"
          - "--disable-agent"
          - "--disable-scheduler"
          - "--disable-cloud-controller"
          - "--flannel-backend=none"
          - "--kube-controller-manager-arg=controllers=*,-nodeipam,-nodelifecycle,-persistentvolume-binder,-attachdetach,-persistentvolume-expander,-cloud-node-lifecycle"  
          - "--service-cidr=10.245.0.0/16"  # This has to be the service CIDR of your main cluster's service CIDR
        volumeMounts:
          - mountPath: /data
            name: data
      - name: syncer
        image: "loftsh/vcluster:0.5.0-beta.0"
        args:
          - --service-name=vcluster-dev
          - --suffix=vcluster-dev
          - --owning-statefulset=vcluster-dev
          - --out-kube-config-secret=vcluster-dev
          - --name=vcluster-dev
          - --tls-san=157.230.65.136
        volumeMounts:
          - mountPath: /data
            name: data
  volumeClaimTemplates:
    - metadata:
        name: data
        namespace: host-vcluster-1
      spec:
        accessModes: [ "ReadWriteOnce" ]
        resources:
          requests:
            storage: 5Gi
