---
apiVersion: v1
kind: Service
metadata:
  name: vcluster-loadbalancer
  namespace: host-vcluster-1
spec:
  selector:
    app: vcluster-1
  ports:
    - name: https
      port: 443
      targetPort: 8443
      protocol: TCP
  type: LoadBalancer
